let images = {
    Useraccount : require("@/assets/account_circle.webp"),
    ActivityColor : require("@/assets/Activity-1.webp"),
    Activity : require("@/assets/Activity.webp"),
    Airplay : require("@/assets/Airplay.webp"),
    BarChart1 : require("@/assets/Bar chart-1.webp"),
    BarChart2 : require("@/assets/Bar chart-2.webp"),
    BarChart : require("@/assets/Bar chart.webp"),
    Bell : require("@/assets/Bell.webp"),
    Database : require("@/assets/Database.webp"),
    Edit : require("@/assets/Edit.webp"),
    Menu : require("@/assets/menu.webp"),
    MessageSquare : require("@/assets/Message square.webp"),
    Notifications : require("@/assets/notifications.webp"),
    PieChart : require("@/assets/Pie chart.webp"),
    Settings : require("@/assets/Settings.webp"),
    Smile : require("@/assets/Smile.webp"),
    Trending : require("@/assets/Trending up.webp"),
    MessageCirce : require("@/assets/Message circle.svg"),
    sett : require("@/assets/Settings.svg"),
    Logout : require("@/assets/Log out.svg"),
    ChatGraph : require("@/assets/Group 25.svg"),
    Logo : require("@/assets/Logo2.svg"),
    Export : require("@/assets/export.svg"),
    imageIcon : require("@/assets/pic.svg"),
    Rectangle : require("@/assets/Rectangle 7.webp"),
    Circle : require("@/assets/Rectangle 8.webp"),
    Star : require("@/assets/Star 1.webp"),
    Color : require("@/assets/color.webp"),
    SearchIcon : require("@/assets/Search.svg"),
    Sad : require("@/assets/Frown.svg"),
    properLogo : require("@/assets/logop.webp"),
    Tick : require("@/assets/TICK.svg"),
    ImageCLip : require("@/assets/Paperclip.svg"),
    Smile2 : require("@/assets/Smile.svg"),
    EditImage : require("@/assets/profileEdit.svg"),
    AuthenticationImage : require("@/assets/authentication.png"),
    google : require("@/assets/google.svg"),
    github : require("@/assets/github.svg"),
    Avatar : require("@/assets/Avatar.webp"),
    twoTicks1 : require("@/assets/ticksTwo1.svg"),
    twoTicks2 : require("@/assets/ticksTwo2.svg"),
    ColoredTick : require("@/assets/coloredTick.svg"),
    singleTick : require("@/assets/singleTick.svg"),
    pending : require("@/assets/pending.svg"),
    AddFriends : require("@/assets/friends.png"),
    requestPending : require("@/assets/PendingRequest.svg")


}

export default images